knot:downgrade to 1.6.5 and support openssl 111
Signed-off-by: lunaticurey <125438787@qq.com>

diff --git a/net/knot/files/knotd.init b/net/knot/files/knotd.init
--- a/net/knot/files/knotd.init
+++ b/net/knot/files/knotd.init
@@ -1,39 +1,45 @@
 #!/bin/sh /etc/rc.common
-#
-# Copyright (C) 2014-2016 CZ.NIC, z.s.p.o. <knot-dns@labs.nic.cz>
-#
-# This is free software, licensed under the GNU General Public License v2.
+START=70
 
-START=50
-USE_PROCD=1
+knot_bin="/usr/sbin/knotd"
+knot_ctl="/usr/sbin/knotc"
+config_file="/etc/knot/knot.conf"
+pid_file="/var/run/knot.pid"
 
-PROG="/usr/sbin/knotd"
-CONFFILE="/etc/knot/knot.conf"
+start() {
+  echo "Starting Knot DNS"
 
-USER="knot"
-USERID="5353"
-RUNDIR="/var/run/knot"
-STORAGE="/var/lib/knot"
+  if [ -e $pid_file ]; then
+     echo "  Already running with PID `cat $pid_file`"
+     return 1
+  fi
 
-fix_perms() {
-	user_exists $USER $USERID || user_add $USER $USERID
-	group_exists $USER $USERID || group_add $USER $USERID
+  $knot_bin -c $config_file -d
 
-	for dir in $RUNDIR $STORAGE; do
-		test -e $dir || {
-			mkdir -p $dir
-			chgrp $USER $dir
-			chmod g+w $dir
-		}
-		chgrp $USER $CONFFILE
-		chmod g+r $CONFFILE
-	done
+  if [ $? -ne 0 ]; then
+    echo "  Failed to start"
+  fi
 }
 
-start_service() {
-	fix_perms
-	procd_open_instance
-	procd_set_param command $PROG -c $CONFFILE
-	procd_set_param respawn
-	procd_close_instance
+stop() {
+  echo "Stopping Knot DNS"
+
+  if [ -e $pid_file ]; then
+    kill `cat $pid_file`
+    rm -f $pid_file
+  else
+    echo "  No PID file $pid_file"
+    return 1
+  fi
+}
+
+restart() {
+  stop
+  start
+}
+
+reload() {
+  echo "Reloading Knot DNS"
+
+  $knot_ctl -c $config_file reload
 }
